defaults: &defaults
  working_directory: ~/react-native-template
  docker:
    - image: circleci/node:8

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
      - run:
          name: Install NPM Packages
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Tests
          command: npm run test
workflows:
  version: 2
  react-native-template-pipeline:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
          filters:
            branches:
              ignore: develop